### ISSUE TITLE
Crashes for DSR's cut maps

### ISSUE THREAD

**Issue by VictorPilgrim** [soulsmods/DSMapStudio#109]
Loading several cut maps for Dark Souls Remastered causes DSMapStudio to crash. The maps are:

99_80_10_00
99_80_10_01
99_80_10_00
99_99_98_09
99_99_98_20
99_99_99_99

Am i doing something wrong? :<

**Comment by kingborehaha** [comment]
Very late "just for the record": you aren't doing anything wrong. These maps just have different data vs other maps which DSMapStudio can't load, and there are concerns regarding making it able to handle these maps without causing issues for normal maps.

For now, I made this branch which is able to do it: https://github.com/kingborehaha/DSMapStudio/tree/DSR-betamap-load

**Comment by kingborehaha** [comment]
Fixes were implemented in #581
