### ISSUE TITLE
Keyboard layout not recognized for hotkeys

### ISSUE THREAD

**Issue by ividyon** [soulsmods/DSMapStudio#141]
I'm on a German QWERTZ keyboard, the biggest difference from QWERTY - besides umlauts - being that Y and Z are swapped.

So, when I Ctrl+Z to "undo", I typically press the button on the right side of T, which is Z for my keyboard layout.

Unfortunately, DSMS seems to assume QWERTY. So, I have to tap the key at the bottom left of the keyboard, where I have Y.

This isn't such a big deal with QWERTZ, but its bound to be problematic with DVORAK, AZERTY etc.

**Comment by kingborehaha** [comment]
1.04 update implemented key bindings so you should be good to go.
