### ISSUE TITLE
DSMS destroys my PC on crash

### ISSUE THREAD

**Issue by ividyon** [soulsmods/DSMapStudio#142]
When I work with DSMS and it has to shut down due to some kind of error, it brings my entire system to a standstill, freezing my mouse, making me unable to go to Task Manager, etc., until it has resolved whatever issue it had and shuts down.

It would be nice if crashing was more graceful.

**Comment by kingborehaha** [comment]
1.04 should try to handle crashes more gracefully, let us know if it still sucks though.
