### ISSUE TITLE
1.07 update

### ISSUE THREAD

**Issue by Ritaku02** [soulsmods/DSMapStudio#185]
Question; how does DSMapStudio currently handle the 1.07 regulation.bin? Is it like Yapped where the new params won't get saved, or do they get saved and they just can't be edited yet?

**Comment by kingborehaha** [comment]
DSMapStudio will not let you modify params deemed too incompatible with current param definitions. If DSMapStudio displays a param in the param editor, it is considered fully modifiable. Like Yapped, all params will be saved to regulation.bin even if they are not modifiable.

DSMapstudio uses a different method than Yapped to determine if a param is safe to edit, so it will load more types atm.

**Comment by Ritaku02** [comment]
Oh, Yapped will still save the new params even if it can't edit them? I read that Yapped won't even save them, while DSMapStudio does but just doesn't let you edit them.

**Comment by kingborehaha** [comment]
There's no reason it wouldn't retain all params, unless Yapped is bugged. There's a vague concern Yapped can't produce a regulation compatible with recent versions of Elden Ring because it hasn't been updated since 1.05 (and in that situation, Elden Ring will use a secret regulation backup instead), but I have yet to hear if that's actually the case.

**Comment by Ritaku02** [comment]
Yeah, it was the creator of CSV Merger that says Yapped won't even save the new params.

**Comment by kingborehaha** [comment]
You can personally verify the params are retained by using https://github.com/sekirodubi/YabberPlus on the regulation.bin.

Gonna go ahead and close this for now. And for future reference, it might be better to ask technical questions like this in the DSMapStudio dev discord at https://discord.gg/CKDBCUFhB3. Or if you have more generalized modding questions, the Fromsoft modding discord at https://discord.gg/mT2JJjx.
