### ISSUE TITLE
DS2 param editing - Crash when trying to edit a param file that DSMapStudio itself created.

### ISSUE THREAD

**Issue by ketwaroo** [soulsmods/DSMapStudio#213]
Okay so this is a weird one. There's 2 bugs. I've attached the crash log and file I think is causing issues.

I'm editing DS2 SotFS params, which I decrypted using Yabber. And modengine to load local files from a `/mods` folder. I have it set up to use loose param files both in the param editor and modenging. Using release 1.04 of DSMapStudio and modengine was compiled from source from https://github.com/katalash/ModEngine.git master branch (I don't think the new modengine works with DS2. or does it?). 

I can edit/save params and changes are picked up by the game just fine as long as I don't do 2 things:

### BUG 1:  `Load default row names` corrupts data. Every time.

If I do `Edit >  Load default row names`, the param data stored in the project folder is instantly corrupted and causes the game to crash on launch.

Workaround is simply not doing that and kind of clicking around blindly a bit instead of relying on informative names.

A good fix would be to just display those default names in the UI but not save them to the files.

### BUG2: reloading a project with previously saved data crahes DSMap Studio

If I edit params and save them. Then exit DSMapStudio for any reason, and relaunch it, DSMapStudio will crash. And the params are resaved automatically and also cause the game to crash on launch.

Seems that as long as the vanilla data was preserved in memory, it will generate correct files. But there may be a bug when trying to read back the the data it saved itself. See attached files.
[Log 2022-10-28--03-40-48.txt](https://github.com/soulsmods/DSMapStudio/files/9890662/Log.2022-10-28--03-40-48.txt)
[ChrCommonParam.zip](https://github.com/soulsmods/DSMapStudio/files/9890695/ChrCommonParam.zip) // zipped so github will let me attach it.

The workaround I'm using
 - never exit DSMapStudio while editing a mod
 - always keep track of param edits as mass edit rules as a separate txt file.
 - If I do have to exit, delete everything in the project folder except the json file
 - rerun every param mass edit from vanilla files again.
 - rinse an repeat.

So while we're on that subject, a feature request would be CLI support for mass editing. so that we could maintain changes to params as a script and rerun them as needed. Something like ```DsMapStudio.exe --project=path/to/project.json --param-mass-edit=path/to/some/file.txt```

**Comment by ketwaroo** [comment]
Bug1 may be solved by #212

**Comment by kingborehaha** [comment]
Bug #2 is being caused by Bug #1 upon loading. And yes, #212 prevents the issue from happening in the first place.

**Comment by kingborehaha** [comment]
Fixed.
