### ISSUE TITLE
Wrong .NET Runtime link from DSMapStudio v1.0.4

### ISSUE THREAD

**Issue by UhuruNUru** [soulsmods/DSMapStudio#215]
I had Microsoft .NET Framework v6.0.9 Desktop Runtime installed already
Your DSMapStudio v1.0.4 said I needed it (Updated?), fair enough, but linked to
Microsoft .NET Framework v6.0.10 ASP ,NET Core

I thought that strange, but installed it, and DSMapStudio v1.0.4 said I needed it (Updated?), again.
Taking what it was saying at face value, I went, with what logic, and gut told me, and updated to
Microsoft .NET Framework v6.0.10 Desktop Runtime

DSMapStudio v1.0.4 then ran without issue, so it appears as though the app, is linking to wrong .Net Install file.
What was a minor niggle for me, could be a serious, roadblock for a new game modder, taking their first steps.

**Comment by Nordgaren** [comment]
Have to report this one to Microsoft. Sorry, bud.

**Comment by kingborehaha** [comment]
Yeah, that message doesn't seem to be something we can trivially change (for some stupid reason).
The requirements page has all the proper links though: https://github.com/soulsmods/DSMapStudio#system-requirements
