### ISSUE TITLE
Can't open multiple DSMapStudio applications at the same time.

### ISSUE THREAD

**Issue by Ullrrific** [soulsmods/DSMapStudio#231]
Merging Regulation files in Elden Ring would be a lot easier if I could open two DSMapStudio projects at once.

Every time I try and open a second DSMapStudio window, the new one just instantly closes on me.

**Comment by kingborehaha** [comment]
Is there any reason you can't use the Compare menu to compare params?

**Comment by kingborehaha** [comment]
This has been fixed.
