### ISSUE TITLE
Attempting automatic merges for regulation.bin (there'll be no issues at all, trust me..)

### ISSUE THREAD

**Issue by JeanNicolasdeLamballerie** [soulsmods/DSMapStudio#236]
## Hello !

I'm building a *simple GUI* that should allow modding through an interface instead of modifying files by hand, to avoid fingers ~(possibly mine)~ being the source of most errors due to misplaced files, commas, or misunderstanding of the way ModLoader or ModEngine operate. 

While everything is looking great when it comes to using the filesystem to move stuff around like animations folders and modify simple txt files, the merging of regulation.bin has been my head-scratcher, because as far as I know, I cannot access the values easily enough to allow merging - or maybe I could through reading a byte stream from each file and checking for differences, but that sounds like a very hacky solution.

### I was wondering if there would be any way to run the software from the command line (and subsequently, from a subprocess in my app) through something like 

`path/to/DSMapStudio --headless --export --modified --path path/to/regulation.bin` 

(and some other options maybe, like the output path, or just have it output to the console since I can safely monitor that)

and then have something like 

`path/to/DSMapStudio --headless --merge path/to/csv path/to/csv2` 

outputting a new regulation.bin somewhere - and possibly throwing a warning/error if the same field is modified. 

I am **really unfamiliar** with C# for now, so implementing the CLI myself would take me quite a while, but I recon the needed features are already available from what I've seen of the software (read file, find modified, return modified as csv. Use csv to generate regulation.bin, rinse and repeat) - just probably not for automation. 

If they already are, I'd love to use them; 

if you can implement them without spending too much time, it'd be perfect; 

and if not but you have some pointers on how I could fork/PR such a feature, I'd love to hear your input on this.
I'm not hoping for that GUI to be anything massive, but being able to have safe backups of my files and have a visual interface to handle mods for myself would be nice; and it's a cool project to work on. 
Cheers :)

**Comment by JeanNicolasdeLamballerie** [comment]
I took the time to look through the source code for a while, and I found a bit of info; such as how (apparently) the data is decrypted (through DecryptERRegulation) but I'm still a bit lost with the amount of code being either generic utils functions or destined to other games.
I'm working out that the byte data is decrypted through a key and reader, but I'm still not sure how to implement that.
(I should mention that I'm currently targeting ER, not previous DS games yet)

**Comment by kingborehaha** [comment]
I would recommend you look at https://github.com/JKAnderson/SoulsFormats/blob/er/FORMATS.md, specifically the example code at the bottom.

**Comment by JeanNicolasdeLamballerie** [comment]
Thanks a lot @kingborehaha !
I've been looking through and that makes a lot of sense - a lot more than it did before, particularly how to single out params and assign them.

The part I'm still struggling with is actually interpreting the byte stream from my regulation files.
As far as I understand, the process will start with something similar to 
`var parambnd = BND3.Read(path);`
Looking at the implementation, it looks something like this :
![image](https://user-images.githubusercontent.com/55099344/201478693-873c59e9-a336-4cf1-8576-ede4e406c519.png)

But trying to read bytes from the regulation.bin file doesn't yield any worthwile result, just messed up strings; I'm fairly confident that's because the bin file is still encrypted and needs to be transformed first (and re-packed later) based on this implementation : 
![image](https://user-images.githubusercontent.com/55099344/201478924-a90b359b-767a-4b36-8d4a-3bc5ed63f0ea.png)

I still need to understand how the `DecryptByteArray ` method works to make something usable, as it uses a bunch of encryption (naturally),  so I can see if I can reproduce something like that.
I'll see how to make my own implementation and how it handles in Dart, and if I don't have any issues use it, otherwise I'll look to directly use the DsMapStudio code (maybe try to isolate and compile part of it into a single utility to do the merging blindly).

Thanks for the heads up 👍 :)

**Comment by JeanNicolasdeLamballerie** [comment]
I'm still having some issues, but I'm not totally certain whether it's because of my own decryption that is failing, or because I need to operate the decompression already.

First off, the crypto library I'm using sometimes throws a ` 'The decrypted bytes have invalid PKCS7 padding length in the end: 0` when trying to decrypt the original .bin file of the game (but not the modded ones ?). Simply commenting the error had output that made sense, so I haven't looked too far into it yet.


The one weird part is that most utils related to ER seem to manipulate a BND4 file; but the reader's first four bytes are usually "DCX ", another format (apparently compressed ?). I also get some string, then data that is clearly not in ASCII; I'm still trying to figure out how to interpret the headers.

It looks something like this :
![image](https://user-images.githubusercontent.com/55099344/201534196-8333727d-f0ab-4243-b370-7be6f2420491.png)


I'll try to mimic the decompression logic then come back; if the decryption is fine, I'm guessing the BND4 files (& other PARAMS) will be contained inside the decompressed file.

**Comment by kingborehaha** [comment]
I'm personally not terribly familiar on the decryption side of things, but if you'd like you can join the Fromsoft modding discord for help (likely from the people who made these libraries to begin with),: https://discord.gg/mT2JJjx

**Comment by JeanNicolasdeLamballerie** [comment]
Thanks Kingbore ! I did join and will bug people in there 😺 .
I'll keep this issue open and update it with a link to the actual merger if it's stable enough since I think I'll create it as a CLI/exec anyway, it'll be available for ease of use for developers.

**Comment by Philiquaz** [comment]
Closing this issue due to lack of updates.
Massedit is currently in a position to perform primitive param merges.
