### ISSUE TITLE
[Featute idea ? ] Merging Regulation.bin ; Effortlessly ;

### ISSUE THREAD

**Issue by brissonsean** [soulsmods/DSMapStudio#344]
Yea i was doin some Regulation.bin merging the other night and i was thinking if we would have a Button to;

1.Copy every single MODIFIED row/Values;.CSV from the F1RST Regulation1.bin to a temporary space
2.Copy every single MODFIED row/Values;.CSV from the S2CND Regulation2.bin -> Overwrite the F1RST Regulation1.bin
3.Copy The Values stored from step (1.) BACK onto the F1RST Regulation1.bin

; So basicly we couldnt be able really to; break the first Regulation.bin anything merging Would only be non-overlapping since we reaplied the F1RST .bin Values in case the S2CND.bin DID overlap.

**Comment by Philiquaz** [comment]
Instead of selecting "modified" you can search for "mergeable" which filters out any conflicting rows.

**Comment by Philiquaz** [comment]
(I should note, this is mergeable when you have the second param loaded for comparison)

**Comment by Philiquaz** [comment]
Alternatively, simple taking rows and inserting them in the opposite order will create the same effect - the added rows will guarantee the 2nd mod's rows are all accounted for.

**Comment by brissonsean** [comment]
AHAH ! i was wandering Why something so simple Wasn't already there; for such the small brain i have; there was now way to figure this out other wise at least for me at this time :D 

Thx this is gonna speed up things a lil alot :)

**Comment by brissonsean** [comment]
AH but the thing is, Conflicting Rows ; Doesnt mean They are ACTUALLY conflicting ; i think? 
![image](https://user-images.githubusercontent.com/77543961/214231596-59768eca-4406-496b-84ad-2e9a6d2151b6.png)
Vanilla Values are not assumed as mergeable since they are Values still.
i think if the values are = to the Vanilla values, then they should be not taken into consideration as Conflicting since they are Vanilla, right? We have Vanilla comparation so why would be be conflicting with Vanilla anyway 🤣 we are modding <3 XD
![image](https://user-images.githubusercontent.com/77543961/214231773-2b581d57-1875-4224-be01-723d28245548.png)

or so i believe  ;i'm not sure ^^' let me know 😁
