### ISSUE TITLE
Doesnt Run on Windows 11

### ISSUE THREAD

**Issue by AlexMcClay** [soulsmods/DSMapStudio#364]
I downloaded the latest version and I have .NET installed (downloaded the version the app told me to download) And the app still asks me to install .NET

**Comment by Philiquaz** [comment]
Ensure you have the .net DESKTOP runtime and the ASP.net runtime

**Comment by AlexMcClay** [comment]
Thanks, that actually fixed it, for some reason it worked this time. I downloaded the same file and installed it again and it worked
