### ISSUE TITLE
DS2: SotFS - ItemLotParam2_XXX is gone

### ISSUE THREAD

**Issue by themelektaus** [soulsmods/DSMapStudio#369]
When I create a new project with "Loose Params" flag enabled, ``ItemLotParam2_XXX`` is not extracted.

### v1.07
![image](https://user-images.githubusercontent.com/6460338/221946289-7d79ee61-d551-4c8c-829f-37e88646c8a2.png)

When I try to select a line in an existing project with the extracted params, ``newParam`` is null.

![image](https://user-images.githubusercontent.com/6460338/221947446-69578b8a-a762-4426-aa40-3bca955b6ece.png)

In the previous version it still works:

### v1.06
![image](https://user-images.githubusercontent.com/6460338/221945955-33b926a7-ba2e-4c5e-9702-e6e7fea7f218.png)

If you need more information, just let me know.

**Comment by Philiquaz** [comment]
Looks like an oversight made the paramdef unfindable, and looseparams are still being shown when not having paramdefs. Likely a unique quirk of DS2's special param loading code.
Working on fixes for both as we speak.

**Comment by Philiquaz** [comment]
fixed with #370
