### ISSUE TITLE
ER - BuddyParam isn't being loaded 

### ISSUE THREAD

**Issue by believeinyuna** [soulsmods/DSMapStudio#379]
every time i load a regulation.bin for merging, buddyparam is missing and i get a warning. making new projects and trying again doesn't seem to fix it. when i open the regulation.bin in another tool (YRB SE), buddyparam shows up.

![image](https://user-images.githubusercontent.com/27219533/224005996-8c0653d6-9a52-412b-a910-c67e63abce40.png)

**Comment by Philiquaz** [comment]
Your BuddyParam is corrupt. Yapped opens it because yapped is the thing corrupting it.

**Comment by Philiquaz** [comment]
Effectively, the version of BuddyParam is from a previous version of the game. The format of BuddyParam has changed but Yapped doesn't respect this, and saves as though it is still old-format. The game will be missing data from BuddyParam. Mapstudio on the other hand will simply not load the param as it doesn't match the expected format for the parambnd version number.
