### ISSUE TITLE
ER - Could not apply ParamDef for SoundCutsceneParam.param

### ISSUE THREAD

**Issue by ltarnowski1** [soulsmods/DSMapStudio#385]
As in the tittle, I am getting that warning creating new project, please describe exactly how can I fix that. I am using newest 1.06 Map Studio, ModEngine 2, Elden Ring 1.08.1

**Comment by kingborehaha** [comment]
Either your project regulation.bin or program regulation.bin contains out of date param files.

**Comment by ltarnowski1** [comment]
so should I update my regulation.bin from modyfication ? I wanted to do it but it throws this warning after project creation, should I ignore it and try to update regulation.bin ?
