### ISSUE TITLE
Label "UnkA0[3]" as "Shadow Model Cull Flip" for spotlights

### ISSUE THREAD

**Issue by RunDevelopment** [soulsmods/DSMapStudio#386]
The "UnkA0[3]" property of spotlights is a boolean called "Shadow Model Cull Flip". Please label the property as such in DSMS.

### Background

While playing around with spotlights in DS3, I noticed an artifact. Their shadows would have these weird edges where they start. I recognized this from the time I played around with directional shadows from the sun. For directional light shadows, there is an option called "Shadow Model Cull Flip" that has the following effect:

![image](https://user-images.githubusercontent.com/20878432/225039483-65450867-39b5-4093-bc77-b80fd0032d34.png)
![image](https://user-images.githubusercontent.com/20878432/225039518-82fd0114-ed1d-44e8-be82-989fec5a2f6c.png)

Since shadows with this effect enabled are a little broken, it's disabled for all directional light sources in the game.

So when I saw this artifact when enabling shadow casting for spotlights, I knew what the issue was.
![image](https://user-images.githubusercontent.com/20878432/225040109-6c614476-0768-47cd-8b9f-ca9e70f971ee.png)

So I just tried out setting properties with the value 1 (true) to 0 (false), and UnkA0[3] did the trick.
![image](https://user-images.githubusercontent.com/20878432/225041005-9010dc18-85cf-424e-b79e-7f556a58efb6.png)

Note that I didn't just report this after getting it to work once. Setting UnkA0[3] to 0 to fix the shadows of spotlights works for all spotlights in DS3 that I tried (>20). So I am fairly confident that my finding is correct. While most spotlights in DS3 have UnkA0[3] set to 1 (because they also have shadow casting disabled), I found one with UnkA0[3] set to 0 and shadow casting enabled: the spotlight that lights up the boss arena of Aldrich.

Also note that what I said about UnkA0[3] applies to spotlights. I haven't tested it for any other types of lights. However, it's likely that it's the same for other types.

**Comment by Philiquaz** [comment]
Very nice detective work. Probably will check with Kata if that's the perfect naming for it but this is great information nonetheless. Thank you!

**Comment by kingborehaha** [comment]
I finally noticed this (sorry for the delay), it will be in 1.09.1. Thanks for the info.

**Comment by RunDevelopment** [comment]
Thank you @kingborehaha!

**Comment by RunDevelopment** [comment]
Actually, please reopen this @kingborehaha.

It's still called "UnkA0[3]" and it's still a byte in 1.09.1, so the issue hasn't been fixed.

![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/837c62ee-cb57-417c-8374-65b891c822c2)

**Comment by kingborehaha** [comment]
@RunDevelopment oh oops, sorry. It was wrong to say it would be in 1.09.1 - but it is in [master](https://github.com/soulsmods/DSMapStudio/blob/1240f401396f91c98ecddd6ba98fc37bdf7cc4b4/src/Andre/SoulsFormats/SoulsFormats/Formats/BTL.cs#L301C27-L301C28).

There was a slip up with moving over SoulsFormats changes over to the 1.09.1 branch. I promise this will _eventually_ be in a release though 🥺.
