### ISSUE TITLE
Increase contrast of differing param color

### ISSUE THREAD

**Issue by oblivioncth** [soulsmods/DSMapStudio#408]
When comparing properties between different regulation.bin files or rows, any that differ are marked with a different color than the default; however, this color does not standout from the default significantly and is easy to miss. I figure this highlighting of differing fields should be more apparent at a glance.

![Contrast](https://user-images.githubusercontent.com/24661585/230046331-3575fba6-943c-444c-98ea-81aeca1a89ad.PNG)
_Top, no difference highlight, bottom, difference highlight._

I'm wondering if this is perhaps only an issue on Dark Mode as I haven't tried to force the application to use Light Mode and if it uses the same highlight color there then it of course would stand out a lot more.

**Comment by kingborehaha** [comment]
This will be improved with https://github.com/soulsmods/DSMapStudio/pull/582. Thanks for the report!
