### ISSUE TITLE
FYI: Multiple Antivirus detection of file 'DSMapStudio.dll'

### ISSUE THREAD

**Issue by Escalios** [soulsmods/DSMapStudio#450]
Your DSMapStudio.dll file is flagged as malicious for some reason, and I've told them and provided your file to my Antivirus provider (Bitdefender) to "review" if it is really malicious or its just False Positive.
For other Antivirus providers, you will have to do it by yourself if you want them to remove detection.

Bitdefender will remove detection of your file within 72hrs if they think your file is safe. (Up to 7 AV providers that use Bitdefender's Antivirus Engine, without any guarantee)
If not, you might want to figure out what is cause of this problem. Because current version has much more detections compared to previous 1.06 version.

VirusTotal (1.08): https://www.virustotal.com/gui/file/4f748d0e08a4c5ad83a9c6c5b9ab2095b7bfeaffb59c71110896835ee2414654
VirusTotal (1.06): https://www.virustotal.com/gui/file/92489fd1fbe6a2bfdc115d70c81b789051a9aaf96a2fa427fad32229ef85683a

**Comment by Philiquaz** [comment]
Current version probably receives more warnings because it's had less time to be voted false-positive than the previous version.
You can see the sourcecode, and that little has changed wrt to param reload, soapstone integration, and any other IO.

**Comment by Escalios** [comment]
I have confirmed they (Bitdefender) have removed your file from detection.
![image](https://user-images.githubusercontent.com/94261388/235370620-c43ac321-878c-47b0-a62e-d8916b930ec7.png)
