### ISSUE TITLE
could not find param file

### ISSUE THREAD

**Issue by Hanse666** [soulsmods/DSMapStudio#454]
hi , im new here , i download dsmapstudio when i open , it said could not find param file and crash , i tried to delete and extract a new one but still get "not find param file and crash" , sorry for my english

**Comment by Philiquaz** [comment]
Sounds like it's trying to open a previous project and that project's setup is missing files.
Try looking in appdata/local/dsmapstudio/config.json and checking the last project. From there, make sure the vanilla game it's referencing has its param files

**Comment by Hanse666** [comment]
I do exactly what you said and it working again , thanks you sir .
