### ISSUE TITLE
Crash on start up Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by KyRLykaios** [soulsmods/DSMapStudio#467]
I've installed  .NET 7 Desktop runtime AND the .NET 7 ASP.NET core runtime

DSMapStudio Version 1.08.0
Object reference not set to an instance of an object.
   at StudioCore.MapStudioNew..ctor() in D:\a\DSMapStudio\DSMapStudio\StudioCore\MapStudioNew.cs:line 99
   at DSMapStudio.Program.Main(String[] args)

**Comment by Philiquaz** [comment]
Try removing the current config file in appdata/local/dsmapstudio

**Comment by KyRLykaios** [comment]
That fixd the issue! thanks!

**Comment by kingborehaha** [comment]
Would it be possible for you to upload the config files you deleted? 
DSMapStudio_Config.json and DSMapStudio_Keybinds.json

**Comment by KyRLykaios** [comment]
Gotcha!
