### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by OmakMohammed** [soulsmods/DSMapStudio#518]
It crashes instantly after starting it up with no error showing. When I launch it, it shows white screen for about 3 sec and closes.

and yes I installed every requirements

**Comment by Philiquaz** [comment]
This means the vulkan renderer is failing to start. Make sure it's being launched on an nvidia or amd non-integrated gpu. One troubleshooting solution that sometimes works is disabling the integrated graphics device in devicemanager

**Comment by OmakMohammed** [comment]
I have amd gpu installed and there is no integrated graphics device showing in device manager and I don't know what's causing it

**Comment by kingborehaha** [comment]
What do the error messages say in windows event viewer?

**Comment by OmakMohammed** [comment]
I fixed it, All I had to do is degrade my amd adrenalin

**Comment by CHAMPLOOx** [comment]
> It crashes instantly after starting it up with no error showing. When I launch it, it shows white screen for about 3 sec and closes.
> 
> and yes I installed every requirements

Same

**Comment by CHAMPLOOx** [comment]
I have all the requirements but for some reason, DSMapStudio opens to black screen for three seconds and then crashes to desktop.
