### ISSUE TITLE
Hot reload is greyed out for Sekiro

### ISSUE THREAD

**Issue by humam2104** [soulsmods/DSMapStudio#521]
![image](https://github.com/soulsmods/DSMapStudio/assets/41898465/4ea293d7-b5fa-4b1f-bffa-3c601cc0480f)
I don't know why but I can't select hot reload. This problem only happens with sekiro. 
Elden Ring, Dark Souls 3 didn't have this problem.

I tried version 1.06 and 1.08

**Comment by kingborehaha** [comment]
Param hot reloading is not available for Sekiro at this time.

**Comment by humam2104** [comment]
Is there any way you can add it? Thanks.
