### ISSUE TITLE
DSMapStudio does not apply changes to the game

### ISSUE THREAD

**Issue by OxxyLix** [soulsmods/DSMapStudio#602]
so there is no normal guides for it. Moved and duplicated some enemies = no changes in game. Then found out about mod engine 2. It also doesn't work :), but mannually replacing created regulation (data0.bdt) file applies only param changes in-game. No changes to the map whatsoever. Have no idea

**Comment by Philiquaz** [comment]
Mapstudio doesn't take responsibility for making the game load your modded files. Modengine is the ideal tool for making this happen, so I recommend hunting around for a more in-depth tutorial on setting it up, particularly for ds3 1.15.2 as you might need to downpatch. I'm not even sure if the UXM patch works on 1.15.2

**Comment by OxxyLix** [comment]
> Mapstudio doesn't take responsibility for making the game load your modded files. Modengine is the ideal tool for making this happen, so I recommend hunting around for a more in-depth tutorial on setting it up, particularly for ds3 1.15.2 as you might need to downpatch. I'm not even sure if the UXM patch works on 1.15.2

That's the strange part. I saw some vides in which guys just made edits to the map in DsMapStudio, and did nothing else and the changes happened. That's why I thought I did not need dsmodengine 2. I also tried every method, Tried neest mod engine 2 (supports 1.15) on 1.15 ds 3. then downpatched ds 3 to 1.12. Didn't work. Tried older mod engine 2 for 1.12. same stuff. ok, will continue seeking

**Comment by Philiquaz** [comment]
me2 has only ever supported 1.15 or higher
the edits made apply because modengine will load files from the same directory mapstudio saves to (this is why mapstudio saves to a different folder in the first place)
if you're having issues with me2, you can try classic modengine, which again is made for 1.15.0

**Comment by OxxyLix** [comment]
> me2 has only ever supported 1.15 or higher the edits made apply because modengine will load files from the same directory mapstudio saves to (this is why mapstudio saves to a different folder in the first place) if you're having issues with me2, you can try classic modengine, which again is made for 1.15.0

ok thx, i'll try

**Comment by kingborehaha** [comment]
@OxxyLix are you still having issues?

**Comment by kingborehaha** [comment]
Please open a new issue if you're still having problems.
