### ISSUE TITLE
Certain DS2 Maps not able to be loaded

### ISSUE THREAD

**Issue by MilesPrower1** [soulsmods/DSMapStudio#668]
In my Dark Souls 2 Project I am unable to load several maps (e.g., Things Betwixt, Majula, Lost Bastille, No man's wharf) but I am able to load maps like Brume Tower and Forest of the fallen giants and I am unsure as to why.

I ripped my game with uxm and made no further changes to the files and created a project as per instruction, is there a console or anything I can use to diagnose the issue I'm having? 

Thank you.

**Comment by Philiquaz** [comment]
Can you confirm if you are modding ds2 or sotfs?
Do you have textures enabled?
If there is an error message, can you share it?

**Comment by MilesPrower1** [comment]
sotfs

Yes

No error message appears when I try to load the map

**Comment by Philiquaz** [comment]
sotfs - good, that's the target
textures - try with them off. might be we're not reading the texture right and it's crashing the renderer somehow
no error message - says it's either deep rendering issue or something outside the .net runtime. maybe an overlay is crashing it, or some other injection.

**Comment by kingborehaha** [comment]
@MilesPrower1 do you still have issues in the latest release?

**Comment by kingborehaha** [comment]
Closing this. If you still have problems, open a new issue.
