### ISSUE TITLE
What do I need to do to get DSMS working for Elden RIng?

### ISSUE THREAD

**Issue by Question2** [soulsmods/DSMapStudio#670]
Following the instructions, i have used UXM Selective Unpacker to unpack the Elden Ring files. I then opened DSMS, but i don't see any way to edit equipment stats, spells, things like that. What am I missing? Someone told me i would need to edit things inside regulation.bin, but i do not see any way for me to do that with DSMS.

**Comment by Philiquaz** [comment]
You need to create a project (using a name, a mod/project folder and the game folder), and head to the params screen. From there you can find equipparams etc and begin modding.
Saving will save files to the mod folder, ready to be loaded with modengine.
