### ISSUE TITLE
Crash on Creating New Project

### ISSUE THREAD

**Issue by NateHevens** [soulsmods/DSMapStudio#719]
Trying to set it up with Elden Ring using this tutorial: https://www.nexusmods.com/eldenring/articles/174

I carefully reviewed the requirements here to ensure I had everything I needed to ensure this would work. I did unzip the program to an external hard drive (the same hard drive all my Steam games are stored on because I need to upgrade my internal drive but can't afford to right now... and I have 14 TBs on my external hard drive).

Every single time I try to create a new project, I first get the following message:
"Attempted to save project files to [folder path] for manual recovery. You must replace your project files with these recovery files should you wish to restore them. Given the program has crashed, these files may be corrupt and you should backup your last good saved files before attempting to use these."

I click Ok, and the game closes. Here's the crash log:

> DSMapStudio Version 1.09.0
> 
> The input data is not a complete block.
> 
>    at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1, Span`1)
>    at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[], Int32, Int32)
>    at System.Security.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[], Int32, Int32)
>    at System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(Boolean, CancellationToken)
>    at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
>    at System.Security.Cryptography.CryptoStream.Dispose(Boolean)
>    at System.IO.Stream.Close()
>    at SoulsFormats.SFUtil.DecryptByteArray(Byte[] key, Byte[] secret) in ./SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 613
>    at SoulsFormats.SFUtil.DecryptERRegulation(String path) in ./SoulsFormats/SoulsFormats/Util/SFUtil.cs:line 530
>    at StudioCore.ParamEditor.ParamBank.LoadParamsERFromFile(String path) in ./StudioCore/ParamEditor/ParamBank.cs:line 830
>    at StudioCore.ParamEditor.ParamBank.LoadParamsER(Boolean partial) in ./StudioCore/ParamEditor/ParamBank.cs:line 792
>    at StudioCore.ParamEditor.ParamBank.<>c__DisplayClass71_0.<ReloadParams>b__0() in ./StudioCore/ParamEditor/ParamBank.cs:line 914
>    at StudioCore.Editor.TaskManager.LiveTask.<CreateTask>b__15_0() in ./StudioCore/Editor/TaskManager.cs:line 126
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object)
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )

I am 99.9% sure this is going to be an issue that is entirely my fault, but I fully admit to my stupidity... I don't know what.

**Comment by kingborehaha** [comment]
The game or project regulation.bin might be corrupt? Try verifying game files through steam and redownload the mods.

**Comment by kingborehaha** [comment]
@NateHevens if you still have issues, make a new issue report.
