### ISSUE TITLE
1.09 DSMapStudio crashes when loading Stormveil Castle

### ISSUE THREAD

**Issue by isshininu** [soulsmods/DSMapStudio#723]
1.09 DSMapStudio lost ability to load certain ER maps without crash (m10_00_00_00 as example of one). Textures off/on doesn't matter

**Comment by kingborehaha** [comment]
Please show the error message and confirm it does work if you go back and use an older version of DsMapStudio (and say which version it was)

**Comment by isshininu** [comment]
> Please show the error message and confirm it does work if you go back and use an older version of DsMapStudio (and say which version it was)

1.08.2 works fine, error message:
same as in this issue https://github.com/soulsmods/DSMapStudio/issues/719, "attempted to save project files" etc
even thought I just loading map and not creating new proj

**Comment by kingborehaha** [comment]
The low requirements EXE can only be used for params and text editing, it doesn't support maps or models.

**Comment by isshininu** [comment]
> The low requirements EXE can only be used for params and text editing, it doesn't support maps or models.

I swear I tried this with regular exe
Anyway, I not only misspelled location name (it was Leyndell royal capital which was not crashing), but also it seems increasing buffer limits resolved this issue (I guess 1.09 required bigger buffer limit for map?)
