### ISSUE TITLE
Search Properties does support arrays and nested fields

### ISSUE THREAD

**Issue by RunDevelopment** [soulsmods/DSMapStudio#739]
I wanted to search for all collisions that enable a specific gparam file. The ID of those files is stored in "EventIDs[0]", so I wanted to search  for all EventIDs[0] with the value 5, but it doesn't work.

![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/0f1527bf-28c7-4165-bd95-227924d3dc2c)

![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/c5a314c2-85bc-4a1c-9285-8a2312ce27b3)

Selecting the property value and hitting Ctrl+F will search for "EventIDs" instead which also doesn't work.

It seems like Search Properties does not support nested fields (e.g. Gparam > LightSetID has the same issue) and arrays (e.g. DrawGroups always seems to search for the [0] element).

**Comment by kingborehaha** [comment]
#687 makes improvements to MSB property search to handle things better.

**Comment by RunDevelopment** [comment]
Very nice! Thanks @kingborehaha! 

Is there any particular reason why this PR has been left open for a month?

**Comment by kingborehaha** [comment]
Mostly neglect, but also the feature wasn't in a release until last week 😔

**Comment by RunDevelopment** [comment]
I confirmed that searching properties now works as expected. Thank you @kingborehaha!
