### ISSUE TITLE
DSParamStudio Will Not Let Me Hot Reload 

### ISSUE THREAD

**Issue by Terra-Codes** [soulsmods/DSMapStudio#754]
despite my best efforts searching for a reason online I cannot tell what is going wrong. Every time I hot reload it tell me the task failed and I've reinstalled twice just to make sure that wasn't the issue, am I missing something?

**Comment by kingborehaha** [comment]
Param Studio is defunct and has been replaced with DSMapStudio, and I sincerely hope you're using the latest version of DSMapStudio which can be found here: https://github.com/soulsmods/DSMapStudio/releases

If that's already the case: when you hot reload, what error message say? You can open up the logger by clicking the arrow button at the top center of the window to get more information.

**Comment by kingborehaha** [comment]
Some things regarding hot reloading has been rewritten since this issue. If you're still having problems, open a new issue.
