### ISSUE TITLE
DSMapStudio will not mark what is "changed" on the Param Editor on sucessive boots thinking it might be "new original values"

### ISSUE THREAD

**Issue by Algester** [soulsmods/DSMapStudio#770]
![Screenshot 2023-11-19 143107](https://github.com/soulsmods/DSMapStudio/assets/6236070/b0d7627c-4330-42c4-9120-cd9d1ce67870)
![Screenshot 2023-11-19 143124](https://github.com/soulsmods/DSMapStudio/assets/6236070/4d4894d1-1377-4f99-9cd4-4b5abd11e61a)

without a comparison .bin file at least thats how the program thinks right now I'm not sure how to "reset" it

**Comment by Philiquaz** [comment]
When you specify the game exe to use, this dictates which files to treat as vanilla. There is a warning regarding the use of the game directory as a project directory.
To see the difference between permanently, you need both versions of the files, and this means the project directory cannot be the game directory.

**Comment by Algester** [comment]
ahhh that means I can not have the project directory to be inside the AC6 install location?
IE
D:\Steam\steamapps\common\ARMORED CORE VI FIRES OF RUBICON\Game
D:\Steam\steamapps\common\ARMORED CORE VI FIRES OF RUBICON\Game\mod\DSMapStudio 1.09.1 HOTFIX
