### ISSUE TITLE
How to mass add/remove render groups?

### ISSUE THREAD

**Issue by RunDevelopment** [soulsmods/DSMapStudio#772]
Hello! I recently got into editing the draw groups of maps to make distant views less barren. However, editing draw groups for a lot of objects is quite painful in DSMS. Maybe I'm misunderstanding how the "Render Groups" tab is supposed to be used, but my current workflow for enabling drawing for map objects is like this:

1. Determine the render groups I need from the collision of the places I want the objects to be visible from. That's very easier in DSMS.
2. Select all the render groups I derived from collisions and select only them in the "Render Groups" tab.
3. Take a screenshot of them/try to remember where they are in the grid. Depends on how many there are.
4. Show all and select a singular object I want to have visible.
5. Click "Get Draw", manually select all the render groups I want to have set from before (either from memory or by consulting a screenshot), and "Assign Draw".
6. Go to step 4 until done. 

Painful and slow.

Is there a better way of doing this? The not quite so helpful help doesn't mention anything.

I need some way to (1) define a set of render groups that (2) I can then add/remove from the draw groups of my selected object/objects.

**Comment by kingborehaha** [comment]
You can right click groups to highlight them, and you can assign currently selected groups to any number of map objects without starting from scratch. I've also been meaning to add a feature that lets you select from highlights

**Comment by RunDevelopment** [comment]
> You can right click groups to highlight them

Ah, now the Clear Highlights button makes sense :) Yes, highlights are part of what I need. Thanks! 

The help button should probably mention them...

> you can assign currently selected groups to any number of map objects without starting from scratch.

That isn't useful to me, because it would assign the same rendering groups to all of them. This isn't what I want. The objects I want to change all have different draw groups, so I can't just assign the same to all of them.

Ideally, there would be some way to add the current highlights to the draw groups of the selected objects.

**Comment by kingborehaha** [comment]
Are you aware of CollisionName functionality? This is a field present on most map parts that lets them inherit properties (including drawgroups) from other map parts, typically collision or map pieces.

**Comment by RunDevelopment** [comment]
I was not, but I don't think it will help. I flew around in DS3's Ringed City a bit and found not one map piece with that property. All objects seem to have the field, but it's empty. Only enemies seem to actually use it.

Also, the functionality of CollisionName that you describe isn't 100% what I need either. I want to make map piece (mostly small ones, like patches of foliage and decorations) visible from farther away. So the render groups I want to add are from many different collisions that might not be near to each other. Inheriting drawgroups from *one* collision isn't enough.
