### ISSUE TITLE
Changing Font

### ISSUE THREAD

**Issue by Mstr-Samuel** [soulsmods/DSMapStudio#844]
Hi
I want to translate DS Remastered to my Language, but because font won't support my language glyphs, it's need to change.
I search internet but didn't find a way, can you add changing fonts feature to the software please? or show me a way to do it?
Thanks

**Comment by kingborehaha** [comment]
If you have question about modding rather than DSMapStudio functionality, then you should probably ask in the Fromsoft modding discord server [here](https://discord.com/channels/529802828278005773/529803144281194506/758718957691207771)
