### ISSUE TITLE
Runs on Linux with wine version 9.0 or better

### ISSUE THREAD

**Issue by pickworthi** [soulsmods/DSMapStudio#858]
Not an issue, I know, but I thought the Linux tribe would like to know this.

I have tried DSMapStudio on wine version 7, it crashes with a vulkan error. 
On wine version 8, it loads and displays, but freezes when I open an existing project.

On wine version 9, it just works (TM). 
You can check your vulkan version as follows:

    vulkaninfo | grep -i apiversion

and your GPU device as follows:

    glxinfo | grep -i device

It did not need any fiddling at all, just create a wineprefix using distribution provided wine package, and run it. 
For example:

    mkdir -p <your-wineprefix-path>
    export WINEPREFIX=<your-wineprefix-path>
    wineboot --init
    wine <path-to-DSMapStudio.exe>

I have only tried the parameter editor on Armored Core 6 so far, and it works.

This is big news, at least it is for me :-) I'm hoping that others searching for how to run DSMapStudion on Linux will find this.
Don't expect any feedback, and feel free to just close this issue.

**Comment by Philiquaz** [comment]
Moved some information into the readme, closing the issue for now.
