### ISSUE TITLE
Elden Ring's Fringefolk Hero's Grave "Ulcerated Tree Spirit" boss missing from NpcParam.

### ISSUE THREAD

**Issue by KrohnusMelavea** [soulsmods/DSMapStudio#875]
Game: Elden Ring
DSMapStudio: v1.10.0
Param: v1.10.0.1000

Essentially what the title says. Did a search for "tree spirit" in NpcParam and the boss in Fringefolk Hero's Grave is not in the list. Confirmed it by looking up each boss param's rune count with data on Fextralife, as well as double checking the region scaling applied to each boss.

Screenshot showing list of NPCs that match "tree spirit":
![image](https://github.com/soulsmods/DSMapStudio/assets/31038699/15a45ed5-f623-4da1-99ae-456de55c5de0)

**Comment by Philiquaz** [comment]
Fortunately for the time being, the row will still exist - after all mapstudio is just reading game data. This will just be a case where the name isn't listed in the community-supplied names file.

**Comment by KrohnusMelavea** [comment]
How do you recommend I ascertain which entry refers to which in-game boss / enemy?

**Comment by Philiquaz** [comment]
You might have luck identifying them by any area scaling params, but more than likely you'd need to check the enemy in the map editor and follow it's reference to the param row - there's nothing stopping multiple of them using the same row, after all. Some rows you may find aren't used at all. I recommend the modding discord for further questions of this nature.
