### ISSUE TITLE
How to make graces active by default?

### ISSUE THREAD

**Issue by PatriceLancaster** [soulsmods/DSMapStudio#878]
Trying to do bingo like in bingo brawlers season 3 with my friends and wanted to try making a mod to enable the graces in certain areas of the game by default how would I go about doing this?

**Comment by Philiquaz** [comment]
This question is best asked on the modding discord. You can find a link in-program.
Also, it's not actually in map or param data, prepare yourself for a conversation about emevd, scripting and gameflags. Quite simple, but different tool.
