### ISSUE TITLE
v1.11: Black textures in DS3

### ISSUE THREAD

**Issue by RunDevelopment** [soulsmods/DSMapStudio#914]
I just tested loading DS3 maps and found that some textures are black. This is different from v1.10 where these textures were displayed correctly.

m30_00
![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/33989bbf-bc06-40d6-8f83-4ffd7aa23209)

m32_00
![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/eae67086-fdf8-4d56-a1b1-9976cf71fbb7)

**Comment by Philiquaz** [comment]
Shaders reverted until vertex coloring is worked on again, and a toggle or solution compliant to all games is written.

**Comment by RunDevelopment** [comment]
Thank you!
