### ISSUE TITLE
Hiding meshes in model editor doesn't work

### ISSUE THREAD

**Issue by RunDevelopment** [soulsmods/DSMapStudio#915]
Clicking on the eye icon like in v1.10 does nothing. Ctrl+H also doesn't work and the context menu is empty.

![image](https://github.com/soulsmods/DSMapStudio/assets/20878432/cc9565b0-8207-4fc0-843b-18cb8ab420f1)

**Comment by Philiquaz** [comment]
Looks like the update to imgui changed how text interacts with a selectable - we weren't picking up the click on the icon.
Ctrl-H to my understanding was never added to model editor.
I've created and merged a patch.
