### ISSUE TITLE
Params not showing on specific files

### ISSUE THREAD

**Issue by ZethrasGorgoth** [soulsmods/DSMapStudio#925]
I tried installing both ModEngine2 and DSMapStudio from scratch on a 100% vanilla game. Then I downloaded and installed "Derp Souls" mod for Dark Souls 3 and even though the mod is working in game, when I try to open its Data0.bnd file I get this screen in DSMapStudio:

![image](https://github.com/soulsmods/DSMapStudio/assets/136716991/66b8450a-137a-4f99-a820-7ffd83889359)

This happen wether the game is unpacked or not, but since the mod is working (I made sure of that) I'm inclided to assume that there's kind of an issue with DAMapStudio visualizing this particular file's params (maybe a wrong setting on my end? Other Data0.bnd files seem to work though).

And yes, game is 100% legit, running through Steam, and is updated to the latest version

**Comment by Philiquaz** [comment]
That certainly is curious. They might be able to skip the check for if it's a param file inside the bnd by modifying the file extension and the game might still find it? Seems unlikely.
Do you have a list of warnings in the log about missing paramdefs? Seems more likely they have stripped paramtypes which mapstudio usually uses to match defs (though the game just reads filenames) - I was under the impression a different set of errors would pop up if that was the case, but perhaps not.

**Comment by Philiquaz** [comment]
Seems confirmed on discord this was indeed a case of trimmed paramtypes in the param and the warning log wasn't prominent enough
